-- Exercise 5: Triggers

--------------------------------------------------------------------------------
-- Scenario 1: Automatically update the last modified date when a customer's record is updated.
-- Question: Write a trigger UpdateCustomerLastModified that updates the LastModified column of the Customers table to the current date whenever a customer's record is updated.
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :new.LastModified := SYSDATE;
END;
/

/*
Output/Result:
Trigger UPDATECUSTOMERLASTMODIFIED compiled

-- Verification:
-- BEFORE UPDATE:
-- Customer ID 1: Name = 'John Doe', LastModified = 2026-07-08

-- AFTER UPDATE (UPDATE Customers SET Name = 'Johnathan Doe' WHERE CustomerID = 1):
-- Customer ID 1: Name = 'Johnathan Doe', LastModified = 2026-07-09 (Auto-updated by trigger)
*/


--------------------------------------------------------------------------------
-- Scenario 2: Maintain an audit log for all transactions.
-- Question: Write a trigger LogTransaction that inserts a record into an AuditLog table whenever a transaction is inserted into the Transactions table.
--------------------------------------------------------------------------------

-- Setup: Create AuditLog table to record all transactions
CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(10),
    LogDate DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, AccountID, Amount, TransactionType, LogDate)
    VALUES (:new.TransactionID, :new.AccountID, :new.Amount, :new.TransactionType, SYSDATE);
END;
/

/*
Output/Result:
Table AUDITLOG created
Trigger LOGTRANSACTION compiled

-- Verification:
-- BEFORE INSERT: AuditLog is empty.
-- INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (10, 1, SYSDATE, 150, 'Deposit');
-- AFTER INSERT: AuditLog contains row -> LogID: 1, TransactionID: 10, AccountID: 1, Amount: 150, TransactionType: 'Deposit', LogDate: 2026-07-09
*/


--------------------------------------------------------------------------------
-- Scenario 3: Enforce business rules on deposits and withdrawals.
-- Question: Write a trigger CheckTransactionRules that ensures withdrawals do not exceed the balance and deposits are positive before inserting a record into the Transactions table.
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_balance NUMBER;
BEGIN
    -- Enforce positive amount check for all transactions
    IF :new.Amount <= 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Transaction amount must be strictly positive.');
    END IF;

    -- Enforce withdrawal limits
    IF :new.TransactionType = 'Withdrawal' THEN
        -- Get the current balance of the account
        SELECT Balance INTO v_balance FROM Accounts WHERE AccountID = :new.AccountID;

        IF v_balance < :new.Amount THEN
            RAISE_APPLICATION_ERROR(-20011, 'Insufficient balance. Transaction aborted.');
        END IF;
    END IF;
END;
/

/*
Output/Result:
Trigger CHECKTRANSACTIONRULES compiled

-- Verification 1 (Valid Transaction):
-- INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (11, 1, SYSDATE, 50, 'Withdrawal');
-- Output: 1 row inserted (since Account 1 has balance > 50)

-- Verification 2 (Insufficient Funds Exception):
-- INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (12, 1, SYSDATE, 50000, 'Withdrawal');
-- Output: ORA-20011: Insufficient balance. Transaction aborted.

-- Verification 3 (Non-positive Amount Exception):
-- INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (13, 1, SYSDATE, -100, 'Deposit');
-- Output: ORA-20010: Transaction amount must be strictly positive.
*/
